using SecurityGateway.Application.Gateway;

namespace SecurityGateway.Api.Middleware;

public sealed class SecurityHeadersMiddleware
{
    private readonly RequestDelegate _next;
    private readonly ILogger<SecurityHeadersMiddleware> _logger;
    private readonly string _adminDomain;

    // Strict CSP for the Security Gateway's own admin UI/API. Proxied applications must set their own CSP
    // or have one configured per-domain in the public nginx gateway; a global permissive policy is a bypass risk.
    // Map tiles are loaded from OpenStreetMap; everything else is same-origin.
    private const string AdminCsp =
        "default-src 'self'; " +
        "script-src 'self'; " +
        "style-src 'self' 'unsafe-inline'; " +
        "img-src 'self' data: blob: https://*.tile.openstreetmap.org; " +
        "font-src 'self'; " +
        "connect-src 'self'; " +
        "media-src 'self'; " +
        "object-src 'none'; " +
        "base-uri 'self'; " +
        "form-action 'self'; " +
        "frame-ancestors 'none'; " +
        "upgrade-insecure-requests;";

    private const string PermissionsPolicy =
        "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()";

    public SecurityHeadersMiddleware(RequestDelegate next, ILogger<SecurityHeadersMiddleware> logger, GatewayOptions options)
    {
        _next = next;
        _logger = logger;
        _adminDomain = options.AdminDomain;
    }

    public async Task InvokeAsync(HttpContext context)
    {
        var headers = context.Response.Headers;
        var host = context.Request.Host.Host;
        var isAdminHost = IsAdminHost(host);

        headers.XContentTypeOptions = "nosniff";
        headers.XXSSProtection = "1; mode=block";
        headers["Referrer-Policy"] = "strict-origin-when-cross-origin";
        headers["Permissions-Policy"] = PermissionsPolicy;

        if (isAdminHost)
        {
            // The admin dashboard and its API get a strict CSP. The challenge page's inline script is
            // generated by GatewayMiddleware before this middleware runs, so its CSP is set there.
            headers.XFrameOptions = "DENY";
            headers["Content-Security-Policy"] = AdminCsp;
        }
        else
        {
            // For proxied applications, do not impose a global permissive CSP. Upstream applications
            // should set their own security headers. We only enforce frame protection for non-admin hosts.
            headers.XFrameOptions = "SAMEORIGIN";
            // Intentionally do not set a blanket CSP here. Per-domain CSPs can be configured in the public nginx.
        }

        await _next(context).ConfigureAwait(false);
    }

    private bool IsAdminHost(string host)
    {
        if (string.IsNullOrWhiteSpace(_adminDomain))
        {
            return false;
        }

        return host.Equals(_adminDomain, StringComparison.OrdinalIgnoreCase);
    }
}
